// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

import (
	"database/sql"
	"time"

	null "github.com/guregu/null"
)

type FeedChannel struct {
	ID          int64        `json:"id"`
	Title       string       `json:"title" validate:"required,min=5,max=20"`
	Description string       `json:"description"`
	Link        string       `json:"link" validate:"required,url"`
	Host        string       `json:"host"`
	Published   null.Time    `json:"published" validate:"required"`
	Enabled     bool         `json:"enabled"`
	Created     time.Time    `json:"created"`
	Updated     sql.NullTime `json:"updated"`
}

type FeedChannelItem struct {
	ChannelID int64 `json:"channel_id" validate:"required"`
	ItemID    int64 `json:"item_id" validate:"required"`
}

type FeedChannelLog struct {
	ID         int64        `json:"id"`
	ChannelID  int64        `json:"channel_id"`
	LastUpdate sql.NullTime `json:"last_update"`
}

type FeedChannelTag struct {
	ChannelID int64 `json:"channel_id"`
	TagID     int64 `json:"tag_id"`
}

type FeedGroup struct {
	ID       int64         `json:"id"`
	Name     string        `json:"name"`
	ParentID sql.NullInt64 `json:"parent_id"`
}

type FeedGroupChannel struct {
	GroupID   int64 `json:"group_id"`
	ChannelID int64 `json:"channel_id"`
}

type FeedItem struct {
	ID              int64        `json:"id"`
	Guid            null.String  `json:"guid,omitempty" validate:"required"`
	GuidIsPermalink sql.NullBool `json:"guid_is_permalink"`
	Title           string       `json:"title"`
	Description     null.String  `json:"description,omitempty" validate:"required"`
	Link            string       `json:"link"`
	Author          *string      `json:"author,omitempty" validate:"required"`
	Published       null.Time    `json:"published" validate:"required"`
	Read            bool         `json:"read"`
	Deleted         bool         `json:"deleted"`
	Created         time.Time    `json:"created"`
	Updated         sql.NullTime `json:"updated"`
}

type Tag struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}
